### ISSUE TITLE
Could you make this repository private?

### ISSUE THREAD

**Issue by joukestoel** [SfS-tue/ProgrammingExercises#1]
Dear (ex)-student,

Could you make this repository private?
Some of the exercises you have in this repository are still being used in the course.

Making good exercises is hard work, and hard to get right. That is why we can't come up with a new set of exercises every year. Because of this, it is problematic that you offer this repository.
Your initial goal, help your fellow students in your year, has been met (since it was 4 years ago). The current students following the course do not have to have answers to exercises that are still to come. 
So, please make this repository private.

Thanks in advance!

**Comment by SfSStudent** [comment]
Poof
